import { drizzle } from 'drizzle-orm/neon-http';     // ORM helper for Neon (PostgreSQL) over HTTP
import { neon } from '@neondatabase/serverless';     // Server-less client for Neon DB
import { jobs } from '@/db/schema';                  // Table schema generated by Drizzle 
import { redirect } from 'next/navigation';          // Next.js navigation helper

// Create a Neon client using the connection string from the environment
const sql = neon(process.env.DATABASE_URL!);
// Initialise Drizzle ORM with the Neon client
const db = drizzle(sql);

// Server action
async function addJob(formData: FormData) {
  'use server';                                  // Marks this function as server-only action 

  // Extrat values from the submitted form
  const company = formData.get('company') as string;
  const title = formData.get('title') as string;

  // Insert a new row into the 'job' table
  await db.insert(jobs).values({
    id: crypto.randomUUID(),    // Generate a unique UUID for the job record 
    company,
    title,
    status: 'applied',         // Default status for a newly added job 
  });

  // After inserting, redirect the user back to the home page 
  redirect('/');
}

export default async function Home() {
  // Fetch all job records from the database (runs on the server)
  const allJobs = await db.select().from(jobs);
  
  return (
    <main className="flex min-h-screen flex-col items-center p-24 gap-8">
      <h1 className="text-6xl font-bold">Job Tracker</h1>
      
      <form action={addJob} className="flex gap-4">
        <input name="company" placeholder="Company" className="border p-2" />
        <input name="title" placeholder="Job Title" className="border p-2" />
        <button type="submit" className="bg-blue-500 text-white px-4 py-2">Add</button>
      </form>
       {/* List all jobs retrieved from the job */}
      <ul className="w-full max-w-md">
        {allJobs.map(job => (
          <li key={job.id} className="border-b py-2">
            {job.company} - {job.title} ({job.status})
          </li>
        ))}
      </ul>
    </main>
  );
}